using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.Localization.Settings;
using PackageInfo = UnityEditor.PackageManager.PackageInfo;

namespace GameKit.Localization.Editor
{
    public static class LocaleConstantsGenerator
    {
        const string OutputPath = "Assets/GameKit/Localization/Scripts/LocaleConstants.cs";
        static readonly UTF8Encoding Utf8EncodingWithoutBom = new(false);
        static readonly StringBuilder SourceBuilder = new(512);
        static bool generationScheduled;

        sealed class LocaleAssetPostprocessor : AssetPostprocessor
        {
            static void OnPostprocessAllAssets(
                string[] importedAssets,
                string[] deletedAssets,
                string[] movedAssets,
                string[] movedFromAssetPaths)
            {
                if (!IsExecutingFromPackage())
                {
                    RequestGeneration();
                }
            }
        }

        static void RequestGeneration()
        {
            if (generationScheduled)
            {
                return;
            }

            generationScheduled = true;
            EditorApplication.delayCall += GenerateFromDelay;
        }

        static void GenerateFromDelay()
        {
            EditorApplication.delayCall -= GenerateFromDelay;
            generationScheduled = false;
            Generate();
        }

        static void Generate()
        {
            var locales = LocalizationSettings.AvailableLocales.Locales;
            if (locales.Count == 0)
            {
                Debug.Log("No locales found. Skipping LocaleConstants generation.");
                return;
            }
            
            SourceBuilder.Clear();
            SourceBuilder.AppendLine("// <auto-generated />");
            SourceBuilder.AppendLine("// Generated by LocaleConstantsGenerator. Do not edit manually.");
            SourceBuilder.AppendLine();
            SourceBuilder.AppendLine("namespace GameKit.Localization");
            SourceBuilder.AppendLine("{");
            SourceBuilder.AppendLine("    public partial record Locale");
            SourceBuilder.AppendLine("    {");

            foreach (var locale in locales)
            {
                SourceBuilder.Append("        public static readonly Locale ")
                    .Append(locale.name)
                    .Append(" = new(\"")
                    .Append(locale.LocaleName)
                    .Append("\", \"")
                    .Append(locale.Identifier.Code)
                    .AppendLine("\");");
            }
            
            SourceBuilder.AppendLine();
            SourceBuilder.AppendLine("        public static readonly System.Collections.Generic.IReadOnlyList<Locale> Locales = new[]");
            SourceBuilder.AppendLine("        {");
            foreach (var locale in locales)
            {
                SourceBuilder.Append("            ")
                    .Append(locale.name)
                    .AppendLine(",");
            }
            SourceBuilder.AppendLine("        };");

            SourceBuilder.AppendLine("    }");
            SourceBuilder.AppendLine("}");

            WriteIfChanged(SourceBuilder.ToString());
        }

        static void WriteIfChanged(string source)
        {
            var directory = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            if (File.Exists(OutputPath))
            {
                var existing = File.ReadAllText(OutputPath, Utf8EncodingWithoutBom);
                if (string.Equals(existing, source, StringComparison.Ordinal))
                {
                    return;
                }
            }

            File.WriteAllText(OutputPath, source, Utf8EncodingWithoutBom);
            AssetDatabase.ImportAsset(OutputPath);
        }

        static bool IsExecutingFromPackage()
        {
            var assembly = typeof(LocaleConstantsGenerator).Assembly;
            var packageInfo = PackageInfo.FindForAssembly(assembly);
            return packageInfo != null;
        }
    }
}
