// <auto-generated />
// Generated by LocaleConstantsGenerator. Do not edit manually.

namespace GameKit.Localization
{
    public partial record Locale
    {
        public static readonly Locale Japanese = new("日本語", "ja");
        public static readonly Locale English = new("English", "en");

        public static readonly System.Collections.Generic.IReadOnlyList<Locale> Locales = new[]
        {
            Japanese,
            English,
        };
    }
}
