// <auto-generated />
// Generated by LocalizedStringConstantsGenerator. Do not edit manually.

using GameKit.Localization;

namespace GameKit.Localization.Internal
{
    public static class LocalizedStringConstants
    {
        public static class Button
        {
            public static readonly LocalizedString Back = new(nameof(Button), nameof(Back));
            public static readonly LocalizedString Cancel = new(nameof(Button), nameof(Cancel));
            public static readonly LocalizedString Close = new(nameof(Button), nameof(Close));
            public static readonly LocalizedString License = new(nameof(Button), nameof(License));
            public static readonly LocalizedString Ok = new(nameof(Button), nameof(Ok));
            public static readonly LocalizedString QuitGame = new(nameof(Button), nameof(QuitGame));
            public static readonly LocalizedString Setting = new(nameof(Button), nameof(Setting));
        }

        public static class Language
        {
            public static readonly LocalizedString LanguageSettingLabel = new(nameof(Language), nameof(LanguageSettingLabel));
        }

        public static class ScreenResolution
        {
            public static readonly LocalizedString FullScreen = new(nameof(ScreenResolution), nameof(FullScreen));
            public static readonly LocalizedString ScreenResolutionSettingLabel = new(nameof(ScreenResolution), nameof(ScreenResolutionSettingLabel));
            public static readonly LocalizedString VsyncSettingLabel = new(nameof(ScreenResolution), nameof(VsyncSettingLabel));
        }
    }
}
